http:
  middlewares:
    platform-security:
      headers:
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: same-origin

    oauth-portal:
      forwardAuth:
        address: http://oauth2-proxy-portal:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Preferred-Username
          - X-Auth-Request-Groups
          - Authorization

    oauth-truck:
      forwardAuth:
        address: http://oauth2-proxy-truck:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Preferred-Username
          - X-Auth-Request-Groups
          - Authorization

    oauth-spbu:
      forwardAuth:
        address: http://oauth2-proxy-spbu:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Preferred-Username
          - X-Auth-Request-Groups
          - Authorization

    oauth-dispatch:
      forwardAuth:
        address: http://oauth2-proxy-dispatch:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Preferred-Username
          - X-Auth-Request-Groups
          - Authorization
